// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trip-bundling/CoordinatorDispatchWithTrips.tsx": () => import("../components/mockups/trip-bundling/CoordinatorDispatchWithTrips.tsx"),
  "./components/mockups/trip-bundling/CoordinatorTripBuilder.tsx": () => import("../components/mockups/trip-bundling/CoordinatorTripBuilder.tsx"),
  "./components/mockups/trip-bundling/RestaurantBundled.tsx": () => import("../components/mockups/trip-bundling/RestaurantBundled.tsx"),
  "./components/mockups/trip-bundling/RiderTripStops.tsx": () => import("../components/mockups/trip-bundling/RiderTripStops.tsx")
};
